### ISSUE TITLE
Import error issue

### ISSUE THREAD

**Issue by ShunJianLee** [GeoBeBee/mySystem#1]
@GeoBeBee bro, may i know how you solve the incomplete read issue in python? Can you show the steps to me. Thanks 

pi@raspberrypi:~/jasper $ sudo python jasper.py
Traceback (most recent call last):
  File "jasper.py", line 12, in <module>
    from client import tts, stt, jasperpath, diagnose
  File "/home/pi/jasper/client/tts.py", line 41, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by GeoBeBee** [comment]
I replied to you with:

> I  had the same problem, and then several more, see this:
> https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt

which leads to this:

> `When running ./jasper.py, I got:
> 
>     File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
>         from requests.compat import IncompleteRead
>     ImportError: cannot import name IncompleteRead`
> I actually fixed this by doing:

Which is referenced in your original question:
https://github.com/jasperproject/jasper-client/issues/496

I don't know what more I can offer.
